"""
alerta_perecible_service.py
Read-only async service for AlertaPerecible.
Alerts are generated by a background job, never by direct API call.
"""
from sqlalchemy.ext.asyncio import AsyncSession

from app.exceptions import MajesaError
from app.models.alerta_perecible import AlertaPerecible
from app.repositories import alerta_perecible_repo


async def get_alerta_perecible(db: AsyncSession, id_alerta: int) -> AlertaPerecible:
    alerta = await alerta_perecible_repo.get_alerta_perecible_by_id(db, id_alerta)
    if not alerta:
        raise MajesaError(f"AlertaPerecible {id_alerta} no encontrada", 404)
    return alerta


async def get_alertas_perecibles(
    db: AsyncSession,
    estado: str | None = None,
    id_insumo: int | None = None,
) -> list[AlertaPerecible]:
    return await alerta_perecible_repo.get_alertas_perecibles(
        db, estado=estado, id_insumo=id_insumo
    )
