"""
alerta_perecible.py (router)
Read-only endpoints for AlertaPerecible.
Alerts are generated by a background job.
"""

from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.dependencies.auth import get_current_user
from app.dependencies.roles import require_rol
from app.models.catalogo import Usuario
from app.schemas.alerta_perecible_schema import (
    AlertaPerecibleResponse,
    EstadoAlertaPerecibleEnum,
    EvaluacionPereciblesResponse,
)
from app.services import alerta_perecible_service

router = APIRouter(
    prefix="/alertas-perecibles",
    tags=["Alertas Perecibles"],
)


@router.get("", response_model=list[AlertaPerecibleResponse])
async def listar_alertas_perecibles(
    estado: EstadoAlertaPerecibleEnum | None = Query(None),
    id_insumo: int | None = Query(None),
    db: AsyncSession = Depends(get_db),
    current_user: Usuario = Depends(get_current_user),
):
    return await alerta_perecible_service.get_alertas_perecibles(
        db,
        estado=estado.value if estado else None,
        id_insumo=id_insumo,
    )


@router.get("/{id_alerta}", response_model=AlertaPerecibleResponse)
async def obtener_alerta_perecible(
    id_alerta: int,
    db: AsyncSession = Depends(get_db),
    current_user: Usuario = Depends(get_current_user),
):
    return await alerta_perecible_service.get_alerta_perecible(
        db,
        id_alerta,
    )


@router.post(
    "/evaluar",
    response_model=EvaluacionPereciblesResponse,
    summary="Evaluar perecibles manualmente (solo Administrador)",
)
async def evaluar_perecibles(
    dias_alerta: int = Query(
        3,
        ge=1,
        description="Días mínimos en inventario para generar alerta",
    ),
    db: AsyncSession = Depends(get_db),
    current_user: Usuario = Depends(require_rol("administrador")),
):
    return await alerta_perecible_service.evaluar_perecibles(
        db,
        dias_alerta=dias_alerta,
    )