"""
alerta_perecible_schema.py
Pydantic schemas for AlertaPerecible (read-only; generated by background job).
"""
from datetime import date, datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, ConfigDict


class EstadoAlertaPerecibleEnum(str, Enum):
    activa = "activa"
    resuelta = "resuelta"


class AlertaPerecibleResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id_alerta_perecible: int
    id_insumo: int
    id_stock: int
    fecha_ingreso: date
    dias_en_inventario: int
    estado: EstadoAlertaPerecibleEnum
    accion_sugerida: Optional[str] = None
    fecha_creacion: datetime
    fecha_resolucion: Optional[datetime] = None


class EvaluacionPereciblesResponse(BaseModel):
    """Response schema for the manual perishables evaluation endpoint."""

    alertas_creadas: int
    omitidas: int
    detalle: list[AlertaPerecibleResponse] = []