"""add auditoria table

Revision ID: 549293899c33
Revises: 01c5c2c4763d
Create Date: 2026-06-02 16:00:06.597236
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '549293899c33'
down_revision = '01c5c2c4763d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id_auditoria', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('action_performed', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('tms', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['pos.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_auditoria'),
    schema='pos'
    )
    op.create_index(op.f('ix_pos_auditoria_id_auditoria'), 'auditoria', ['id_auditoria'], unique=False, schema='pos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pos_auditoria_id_auditoria'), table_name='auditoria', schema='pos')
    op.drop_table('auditoria', schema='pos')
    # ### end Alembic commands ###
