"""
alerta_perecible_repo.py
Async repository for AlertaPerecible (read-only via API; generated by background job).
"""
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.alerta_perecible import AlertaPerecible


async def get_alerta_perecible_by_id(
    db: AsyncSession, id_alerta: int
) -> AlertaPerecible | None:
    return await db.get(AlertaPerecible, id_alerta)


async def get_alertas_perecibles(
    db: AsyncSession,
    estado: str | None = None,
    id_insumo: int | None = None,
) -> list[AlertaPerecible]:
    query = select(AlertaPerecible)
    if estado:
        query = query.where(AlertaPerecible.estado == estado)
    if id_insumo:
        query = query.where(AlertaPerecible.id_insumo == id_insumo)
    query = query.order_by(AlertaPerecible.fecha_creacion.desc())
    result = await db.execute(query)
    return list(result.scalars().all())
